// Code generated by go generate; DO NOT EDIT.

package main

const (
	themeTokenTextPrimary     = "#c8ccd4"
	themeTokenTextSecondary   = "#8b93a1"
	themeTokenTextFaint       = "#6b7280"
	themeTokenTextInverted    = "#12141a"
	themeTokenAccent          = "#56b6c2"
	themeTokenAccent2         = "#b392f0"
	themeTokenSuccess         = "#7ee787"
	themeTokenWarning         = "#e5c07b"
	themeTokenDanger          = "#ff7b72"
	themeTokenBorderPrimary   = "#2b2f3a"
	themeTokenBorderSecondary = "#3a3f4b"
	themeTokenBorderFaint     = "#1c1f27"
	themeTokenBorderFocus     = "#56b6c2"
	themeTokenBorderBlur      = "#2b2f3a"
	themeTokenBgSelected      = "#1f2a44"
	themeTokenBgEmphasis      = "#13303a"
	themeTokenBgFailure       = "#3a1414"
	themeTokenBgAction        = "#0f1a12"
	themeTokenBgBar           = "#0c0e13"
	themeTokenBgHeader        = "#161922"
	themeTokenDiffAdd         = "#7ee787"
	themeTokenDiffRemove      = "#ff7b72"
	themeTokenDiffSyntaxTheme = "tokyonight_night"
	themeTokenFontFamily      = "CommitMono Nerd Font"
	themeTokenFontIcons       = "nerd-fonts-status"
	themeTokenGhEnhanceTheme  = "tokyonight"
)
