import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import type { PhaseRunnerFactoryContext, PhaseRunnerRequest } from "../orchestrator/phase-runner.js";

interface DeveloperFileSpec {
  path: string;
  content: string;
}

interface SmokePhaseRunnerOptions {
  developerFiles?: DeveloperFileSpec[];
}

function readOptions(ctx: PhaseRunnerFactoryContext): SmokePhaseRunnerOptions {
  const optionsPath = ctx.config.optionsPath;
  if (!optionsPath || !existsSync(optionsPath)) {
    return {};
  }
  return JSON.parse(readFileSync(optionsPath, "utf-8")) as SmokePhaseRunnerOptions;
}

function writeFileRelative(cwd: string, relativePath: string, content: string): void {
  const absolutePath = join(cwd, relativePath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content, "utf-8");
}

function commitAll(cwd: string, message: string): void {
  try {
    execFileSync("git", ["add", "-A"], { cwd, stdio: "ignore" });
    execFileSync("git", ["commit", "-m", message], {
      cwd,
      stdio: "ignore",
      env: {
        ...process.env,
        GIT_EDITOR: "true",
        GIT_AUTHOR_NAME: process.env.GIT_AUTHOR_NAME ?? "Foreman Test",
        GIT_AUTHOR_EMAIL: process.env.GIT_AUTHOR_EMAIL ?? "foreman@example.com",
        GIT_COMMITTER_NAME: process.env.GIT_COMMITTER_NAME ?? "Foreman Test",
        GIT_COMMITTER_EMAIL: process.env.GIT_COMMITTER_EMAIL ?? "foreman@example.com",
      },
    });
  } catch (error: unknown) {
    const messageText = error instanceof Error ? error.message : String(error);
    if (!messageText.includes("nothing to commit")) {
      throw error;
    }
  }
}

export function createPhaseRunner(ctx: PhaseRunnerFactoryContext) {
  const options = readOptions(ctx);

  return async ({ metadata }: PhaseRunnerRequest) => {
    const cwd = metadata.worktreePath;
    switch (metadata.phaseName) {
      case "explorer":
        writeFileRelative(cwd, "EXPLORER_REPORT.md", "# Explorer Report\n\n## Verdict: PASS\n\nSmoke test noop — no real exploration performed.\n");
        break;
      case "developer": {
        const developerFiles = options.developerFiles ?? [
          { path: "test.txt", content: `generated by ${metadata.seedId}\n` },
        ];
        for (const file of developerFiles) {
          writeFileRelative(cwd, file.path, file.content);
        }
        writeFileRelative(cwd, "DEVELOPER_REPORT.md", "# Developer Report\n\n## Verdict: PASS\n\nSmoke test noop — deterministic developer fixture executed.\n");
        writeFileRelative(
          cwd,
          "RUN_LOG.md",
          `# Run Log\n\n| Timestamp | Phase | Status | Notes |\n|---|---|---|---|\n| ${new Date().toISOString()} | smoke-developer | completed | Deterministic smoke runtime |\n`,
        );
        break;
      }
      case "qa":
        writeFileRelative(
          cwd,
          "QA_REPORT.md",
          "# QA Report\n\n## Test Evidence\n- Command: npm test\n- Tests: 1 passed, 0 failed\n- Output: deterministic smoke runtime\n\n## Verdict: PASS\n",
        );
        break;
      case "reviewer":
        writeFileRelative(cwd, "REVIEW.md", "# Review\n\n## Verdict: PASS\n\nDeterministic smoke review pass.\n");
        break;
      case "finalize":
        writeFileRelative(
          cwd,
          "FINALIZE_VALIDATION.md",
          "# Finalize Validation\n\n## Target Integration\n- Status: SKIPPED\n- Output: Deterministic smoke runtime assumes target branch unchanged after QA.\n\n## Test Validation\n- Status: SKIPPED\n- Output: Validation already covered in QA for unchanged target branch.\n\n## Failure Scope\n- NONE\n\n## Verdict: PASS\n",
        );
        commitAll(cwd, `${metadata.seedTitle} (${metadata.seedId})`);
        break;
      case "troubleshooter":
        writeFileRelative(cwd, "TROUBLESHOOT_REPORT.md", "# Troubleshoot Report\n\nESCALATED\n");
        break;
      default:
        break;
    }

    return {
      success: true,
      costUsd: 0,
      turns: 1,
      toolCalls: 0,
      toolBreakdown: {},
      tokensIn: 0,
      tokensOut: 0,
      outputText: `deterministic-${metadata.phaseName}`,
    };
  };
}
