//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

type tokens struct {
	Text struct {
		Primary   string `yaml:"primary"`
		Secondary string `yaml:"secondary"`
		Faint     string `yaml:"faint"`
		Inverted  string `yaml:"inverted"`
	} `yaml:"text"`
	Accent  string `yaml:"accent"`
	Accent2 string `yaml:"accent2"`
	Success string `yaml:"success"`
	Warning string `yaml:"warning"`
	Danger  string `yaml:"danger"`
	Border  struct {
		Primary   string `yaml:"primary"`
		Secondary string `yaml:"secondary"`
		Faint     string `yaml:"faint"`
		Focus     string `yaml:"focus"`
		Blur      string `yaml:"blur"`
	} `yaml:"border"`
	BG struct {
		Canvas   string `yaml:"canvas"`
		Selected string `yaml:"selected"`
		Emphasis string `yaml:"emphasis"`
		Failure  string `yaml:"failure"`
		Action   string `yaml:"action"`
		Bar      string `yaml:"bar"`
		Header   string `yaml:"header"`
	} `yaml:"bg"`
	Diff struct {
		Add              string `yaml:"add"`
		Remove           string `yaml:"remove"`
		AddBG            string `yaml:"addBg"`
		AddEmphasisBG    string `yaml:"addEmphasisBg"`
		RemoveBG         string `yaml:"removeBg"`
		RemoveEmphasisBG string `yaml:"removeEmphasisBg"`
		SyntaxTheme      string `yaml:"syntaxTheme"`
	} `yaml:"diff"`
	Tools struct {
		GhEnhanceTheme string `yaml:"ghEnhanceTheme"`
	} `yaml:"tools"`
	Font struct {
		Family string `yaml:"family"`
		Icons  string `yaml:"icons"`
	} `yaml:"font"`
}

var hex = regexp.MustCompile(`^#[0-9a-fA-F]{6}$`)

func main() {
	data, err := os.ReadFile("theme/tokens.yaml")
	must(err)
	var t tokens
	must(yaml.Unmarshal(data, &t))
	validate(t)
	write("theme_tokens_gen.go", cockpitTokens(t))
	write("theme/gh-dash.yml", ghTheme(t))
	write("theme/enhance.env", enhanceEnv(t))
	must(os.MkdirAll("theme/diffnav", 0o755))
	write("theme/diffnav/config.yml", diffnavTheme(t))
	write("theme/diffnav.yml", diffnavTheme(t))
	write("theme/delta.gitconfig", deltaConfig(t))
	write("theme/glamour.json", glamourTheme(t))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func write(path, content string) {
	must(os.WriteFile(path, []byte(content), 0o644))
}

func validate(t tokens) {
	values := map[string]string{
		"text.primary": t.Text.Primary, "text.secondary": t.Text.Secondary, "text.faint": t.Text.Faint, "text.inverted": t.Text.Inverted,
		"accent": t.Accent, "accent2": t.Accent2, "success": t.Success, "warning": t.Warning, "danger": t.Danger,
		"border.primary": t.Border.Primary, "border.secondary": t.Border.Secondary, "border.faint": t.Border.Faint, "border.focus": t.Border.Focus, "border.blur": t.Border.Blur,
		"bg.selected": t.BG.Selected, "bg.emphasis": t.BG.Emphasis, "bg.failure": t.BG.Failure, "bg.action": t.BG.Action, "bg.bar": t.BG.Bar, "bg.header": t.BG.Header,
		"diff.add": t.Diff.Add, "diff.remove": t.Diff.Remove, "diff.addBg": t.Diff.AddBG, "diff.addEmphasisBg": t.Diff.AddEmphasisBG, "diff.removeBg": t.Diff.RemoveBG, "diff.removeEmphasisBg": t.Diff.RemoveEmphasisBG,
	}
	for name, value := range values {
		if !hex.MatchString(value) {
			panic(fmt.Sprintf("%s must be #RRGGBB, got %q", name, value))
		}
	}
	if strings.TrimSpace(t.Diff.SyntaxTheme) == "" || strings.TrimSpace(t.Font.Icons) == "" || strings.TrimSpace(t.Tools.GhEnhanceTheme) == "" {
		panic("syntax theme, icon set, and gh enhance theme are required")
	}
}

func cockpitTokens(t tokens) string {
	src := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package main

const (
	themeTokenTextPrimary = %q
	themeTokenTextSecondary = %q
	themeTokenTextFaint = %q
	themeTokenTextInverted = %q
	themeTokenAccent = %q
	themeTokenAccent2 = %q
	themeTokenSuccess = %q
	themeTokenWarning = %q
	themeTokenDanger = %q
	themeTokenBorderPrimary = %q
	themeTokenBorderSecondary = %q
	themeTokenBorderFaint = %q
	themeTokenBorderFocus = %q
	themeTokenBorderBlur = %q
	themeTokenBgSelected = %q
	themeTokenBgEmphasis = %q
	themeTokenBgFailure = %q
	themeTokenBgAction = %q
	themeTokenBgBar = %q
	themeTokenBgHeader = %q
	themeTokenDiffAdd = %q
	themeTokenDiffRemove = %q
	themeTokenDiffSyntaxTheme = %q
	themeTokenFontFamily = %q
	themeTokenFontIcons = %q
	themeTokenGhEnhanceTheme = %q
)
`, t.Text.Primary, t.Text.Secondary, t.Text.Faint, t.Text.Inverted, t.Accent, t.Accent2, t.Success, t.Warning, t.Danger, t.Border.Primary, t.Border.Secondary, t.Border.Faint, t.Border.Focus, t.Border.Blur, t.BG.Selected, t.BG.Emphasis, t.BG.Failure, t.BG.Action, t.BG.Bar, t.BG.Header, t.Diff.Add, t.Diff.Remove, t.Diff.SyntaxTheme, t.Font.Family, t.Font.Icons, t.Tools.GhEnhanceTheme)
	formatted, err := format.Source([]byte(src))
	must(err)
	return string(formatted)
}

func ghTheme(t tokens) string {
	return fmt.Sprintf(`theme:
  colors:
    text:
      primary: %q
      secondary: %q
      inverted: %q
      faint: %q
      warning: %q
      success: %q
    background:
      selected: %q
    border:
      primary: %q
      secondary: %q
      faint: %q
keybindings:
  universal:
    - key: q
      builtin: quit
    - key: "?"
      builtin: help
    - key: /
      builtin: search
    - key: j
      builtin: down
    - key: k
      builtin: up
    - key: ctrl+d
      builtin: pageDown
    - key: ctrl+u
      builtin: pageUp
    - key: h
      builtin: prevSection
    - key: l
      builtin: nextSection
    - key: g
      builtin: firstLine
    - key: G
      builtin: lastLine
    - key: o
      builtin: openGithub
    - key: enter
      builtin: openGithub
    - key: y
      builtin: copyNumber
    - key: Y
      builtin: copyurl
`, t.Text.Primary, t.Text.Secondary, t.Text.Inverted, t.Text.Faint, t.Danger, t.Success, t.BG.Selected, t.Border.Primary, t.Border.Secondary, t.Border.Faint)
}

func enhanceEnv(t tokens) string {
	return fmt.Sprintf("ENHANCE_THEME=%s\n", t.Tools.GhEnhanceTheme)
}

func diffnavTheme(t tokens) string {
	return fmt.Sprintf(`ui:
  sideBySide: true
  icons: %s
  colorFileNames: true
  showDiffStats: true
  hideHeader: false
`, t.Font.Icons)
}

func deltaConfig(t tokens) string {
	return fmt.Sprintf(`[delta]
    syntax-theme = %s
    side-by-side = true
    line-numbers = true
    navigate = true
    minus-style                = syntax %q
    minus-emph-style           = syntax %q
    plus-style                 = syntax %q
    plus-emph-style            = syntax %q
    file-style                 = %q bold
    hunk-header-style          = %q
    line-numbers-minus-style   = %q
    line-numbers-plus-style    = %q
`, t.Diff.SyntaxTheme, t.Diff.RemoveBG, t.Diff.RemoveEmphasisBG, t.Diff.AddBG, t.Diff.AddEmphasisBG, t.Accent, t.Text.Secondary, t.Diff.Remove, t.Diff.Add)
}

func glamourTheme(t tokens) string {
	bold := true
	style := map[string]any{
		"document":    map[string]any{"color": t.Text.Primary},
		"paragraph":   map[string]any{"color": t.Text.Primary},
		"heading":     map[string]any{"color": t.Accent, "bold": bold},
		"h1":          map[string]any{"color": t.Accent, "bold": bold},
		"h2":          map[string]any{"color": t.Accent, "bold": bold},
		"h3":          map[string]any{"color": t.Accent2, "bold": bold},
		"text":        map[string]any{"color": t.Text.Primary},
		"strong":      map[string]any{"color": t.Text.Primary, "bold": bold},
		"emph":        map[string]any{"color": t.Text.Secondary},
		"hr":          map[string]any{"color": t.Border.Primary},
		"link":        map[string]any{"color": t.Accent2, "underline": true},
		"link_text":   map[string]any{"color": t.Accent2},
		"code":        map[string]any{"color": t.Text.Primary, "background_color": t.Border.Faint},
		"code_block":  map[string]any{"color": t.Text.Primary, "theme": t.Diff.SyntaxTheme},
		"item":        map[string]any{"color": t.Text.Primary},
		"enumeration": map[string]any{"color": t.Text.Secondary},
	}
	data, err := json.MarshalIndent(style, "", "  ")
	must(err)
	return string(data) + "\n"
}
